### ISSUE TITLE
Running steps?

### ISSUE THREAD

**Issue by MohdShabaz** [damienbod/AspNetCoreAzureAdAzureStorage#5]
Hi Damien,
Amazing work. I want to build something similar.

I registered my application on azure and added the ClientId and TenantId to the appsettings.json files in both the project solutions. Upon running the application, it asks for admin approval.

1)What should be my next step?

2) Also, why is the clientId in AzureManagementFluent different from AzureAd?
(How can I get the clientId of AzureManagementFluent?)

Thank you,
Regards,
Mohammed Shabaz

**Comment by damienbod** [comment]
Hi @MohdShabaz Thanks

I used 2 app registrations due to the level of the permissions given in each. Would using only security groups be maybe  a better solution?

Greetings Damien

**Comment by MohdShabaz** [comment]
Yes it might be better. Maybe you can consider Microsoft.Identity

**Comment by damienbod** [comment]
Yes, I use Microsoft.Identity

https://github.com/damienbod/AspNetCoreAzureAdAzureStorage/blob/main/AspNetCoreAzureStorageGroups/Program.cs#L35-L37

Greetings Damien
